joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 10.0

joint_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - swiftpro/joint1
    - swiftpro/joint2
    - swiftpro/joint3
    - swiftpro/joint4

passive_joint_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - swiftpro/passive_joint1
    - swiftpro/passive_joint2
    - swiftpro/passive_joint3
    - swiftpro/passive_joint5
    - swiftpro/passive_joint7
    - swiftpro/passive_joint8