joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100.0

passive_joint_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - turtlebot/swiftpro/passive_joint1
    - turtlebot/swiftpro/passive_joint2
    - turtlebot/swiftpro/passive_joint3
    - turtlebot/swiftpro/passive_joint5
    - turtlebot/swiftpro/passive_joint7
    - turtlebot/swiftpro/passive_joint8