joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100.0

joint_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - turtlebot/swiftpro/joint1
    - turtlebot/swiftpro/joint2
    - turtlebot/swiftpro/joint3
    - turtlebot/swiftpro/joint4

joint1_position_controller:
  type: velocity_controllers/JointPositionController
  joint: turtlebot/swiftpro/joint1
  pid:
    p: 1.0
    i: 0.0
    d: 0.0
    i_clamp_min: -1.0
    i_clamp_max: 1.0

joint2_position_controller:
  type: velocity_controllers/JointPositionController
  joint: turtlebot/swiftpro/joint2
  pid:
    p: 1.0
    i: 0.0
    d: 0.0
    i_clamp_min: -1.0
    i_clamp_max: 1.0

joint3_position_controller:
  type: velocity_controllers/JointPositionController
  joint: turtlebot/swiftpro/joint3
  pid:
    p: 1.0
    i: 0.0
    d: 0.0
    i_clamp_min: -1.0
    i_clamp_max: 1.0

joint4_position_controller:
  type: velocity_controllers/JointPositionController
  joint: turtlebot/swiftpro/joint4
  pid:
    p: 1.0
    i: 0.0
    d: 0.0
    i_clamp_min: -1.0
    i_clamp_max: 1.0